version: '3.8'

volumes:
  postgres_data:
  redis_data:

services:

  postgres:
    image: postgis/postgis:13-3.1-alpine
    command: postgres
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 3

  redis:
    image: redislabs/redismod
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  keycloak:
      image: quay.io/keycloak/keycloak:legacy
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: ${DB_DATABASE}
        DB_USER: ${DB_USER}
        DB_SCHEMA: public
        DB_PASSWORD: ${DB_PASSWORD}
        KEYCLOAK_USER: ${KEYCLOAK_ADMIN}
        KEYCLOAK_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      ports:
        - 8080:8080
      depends_on:
        - postgres