version: '3.8'

volumes:
  postgres_data:

services:

  postgres:
    image: postgis/postgis:13-3.1-alpine
    command: postgres
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 3